// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBJeW7mk7a3c659_tZVH27sZuIMUMZf6Q',
    appId: '1:728049217907:web:0fb04565b2315ae2145506',
    messagingSenderId: '728049217907',
    projectId: 'quicksplit-cb005',
    authDomain: 'quicksplit-cb005.firebaseapp.com',
    storageBucket: 'quicksplit-cb005.firebasestorage.app',
    measurementId: 'G-SDWR082C6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoxyaRd2UdiyxTTfIcNCew31JeSO4dRgQ',
    appId: '1:728049217907:android:805f47f8a7121713145506',
    messagingSenderId: '728049217907',
    projectId: 'quicksplit-cb005',
    storageBucket: 'quicksplit-cb005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCe19EKLGTZlY0BeZQA7IjB2uI-et6vos',
    appId: '1:728049217907:ios:71aa4342581577d5145506',
    messagingSenderId: '728049217907',
    projectId: 'quicksplit-cb005',
    storageBucket: 'quicksplit-cb005.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCe19EKLGTZlY0BeZQA7IjB2uI-et6vos',
    appId: '1:728049217907:ios:71aa4342581577d5145506',
    messagingSenderId: '728049217907',
    projectId: 'quicksplit-cb005',
    storageBucket: 'quicksplit-cb005.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBJeW7mk7a3c659_tZVH27sZuIMUMZf6Q',
    appId: '1:728049217907:web:d1c1224cd6589883145506',
    messagingSenderId: '728049217907',
    projectId: 'quicksplit-cb005',
    authDomain: 'quicksplit-cb005.firebaseapp.com',
    storageBucket: 'quicksplit-cb005.firebasestorage.app',
    measurementId: 'G-BCV0WMQS2P',
  );
}
